---
stages:
  - build

compile_document:
  image: 
    name: tubaf_latex
    entrypoint: ["/bin/sh", "-c"]
  stage: build
  script:
    - latexmk -pdf main.tex
  artifacts:
    name: "Masterthesis.pdf"
    paths:
      - main.pdf
    expire_in: 4 week
  tags:
    - latex
