---
stages:
  - build
  - upload

compile_document:
  image: 
    name: git.informatik.tu-freiberg.de:5050/jtoth/thesis-latex:latest
    entrypoint: [""]
  stage: build
  script:
    - latexmk -pdf main.tex
  artifacts:
    name: "$CI_BUILD_ID-$CI_PIPELINE_ID"
    paths:
      - main.pdf
    expire_in: 1 week
  tags:
    - docker

upload_as_page:
  image: 
    name: git.informatik.tu-freiberg.de:5050/jtoth/thesis-latex:latest
    entrypoint: [""]
  stage: upload
  needs: ["compile_document"]
  script:
    - mkdir public
    - mv main.pdf public/
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
  tags:
    - docker
